CREATE TABLE "PLAN_TYPE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(250 CHAR) , 
	"DESCRIPTION" VARCHAR2(2000 CHAR) , 
	"CREATE_DATE" DATE DEFAULT sysdate, 
	"CREATE_USER" VARCHAR2(255 CHAR) , 
	"UPDATE_DATE" DATE DEFAULT sysdate, 
	"UPDATE_USER" VARCHAR2(255 CHAR) 
   )   ;
--------------------------------------------------------
--  DDL for Table TYPE_COMPONENT
--------------------------------------------------------
  CREATE TABLE "TYPE_COMPONENT" 
   (	"ID" NUMBER, 
	"PLAN_TYPE_ID" NUMBER, 
	"NAME" VARCHAR2(250 CHAR) , 
	"DESCRIPTION" VARCHAR2(2000 CHAR) , 
	"CODE" VARCHAR2(2000 CHAR) , 
	"CREATE_DATE" DATE DEFAULT sysdate, 
	"CREATE_USER" VARCHAR2(255 CHAR) , 
	"UPDATE_DATE" DATE DEFAULT sysdate, 
	"UPDATE_USER" VARCHAR2(255 CHAR) , 
	"CSS" VARCHAR2(1000) 
   )   ;
REM INSERTING into PLAN_TYPE
SET DEFINE OFF;
Insert into PLAN_TYPE (ID,NAME,DESCRIPTION,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER) values ('1','Parking',null,to_date('19.07.2023 07:07:59','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 07:07:59','DD.MM.RRRR HH24:MI:SS'),null);
Insert into PLAN_TYPE (ID,NAME,DESCRIPTION,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER) values ('2','Workspace',null,to_date('19.07.2023 07:07:59','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 07:07:59','DD.MM.RRRR HH24:MI:SS'),null);
Insert into PLAN_TYPE (ID,NAME,DESCRIPTION,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER) values ('3','Arrows/Entrance/door',null,to_date('20.07.2023 09:46:28','DD.MM.RRRR HH24:MI:SS'),null,to_date('20.07.2023 09:46:28','DD.MM.RRRR HH24:MI:SS'),null);
REM INSERTING into TYPE_COMPONENT
SET DEFINE OFF;
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('14','2','Seat',null,'<div id="drag" onClick="select()" class="component drag workspace-seat"><div class="workspace-seat-inner"></div></div>',to_date('18.08.2023 10:15:07','DD.MM.RRRR HH24:MI:SS'),null,to_date('18.08.2023 10:15:07','DD.MM.RRRR HH24:MI:SS'),null,'.workspace-seat { width: 40px; height: 40px; background-color: #c6c6c6; border: 1px solid black; border-radius: 10px 10px 0px 0px; margin: 10px; overflow: visible; } .workspace-seat-inner { width: 120%; border: 1px solid black; height: 80%; margin-left: -10%; margin-top: 20%; border-radius: 5px 5px 0px 0px; background-color: transparent; border-left: 4px solid black; border-right: 4px solid black; }');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('16','2','Desk customizable',null,'<div  onClick="select()" id="drag" class="component drag ui-draggable ui-draggable-handle desk-simple horizontal"></div>',to_date('18.08.2023 10:23:59','DD.MM.RRRR HH24:MI:SS'),null,to_date('18.08.2023 10:23:59','DD.MM.RRRR HH24:MI:SS'),null,'.desk-simple {border: 1px solid gray;width: 140px;height: 70px;background-color: beige;text-align: -webkit-center;margin: 10px;border-radius: 4px;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('18','2','Office plant row',null,'<div id="drag" class="component drag workspace-plant-row"><div class="plant-bg"></div><div class="plant-bg"></div><div class="plant-bg"></div></div>',to_date('18.08.2023 10:56:18','DD.MM.RRRR HH24:MI:SS'),null,to_date('18.08.2023 10:56:18','DD.MM.RRRR HH24:MI:SS'),null,'.workspace-plant-row { width: 200px; height: 30px; border: 1px solid black; display: flex;   flex-wrap: nowrap;   flex-direction: row;  background:   radial-gradient(circle at 100% 50%, transparent 20%, brown 21%, black 34%, transparent 35%, transparent),   radial-gradient(circle at 0% 50%, transparent 20%, brown 21%, black 34%, transparent 35%, transparent) 0 -25px; background-color: #DEB99E; background-size: 7px 10px;}.plant-bg {   margin: 0px 1px 0px 1px; border: 2px solid #7BC17E; width: 33%; height: 100%; border-radius: 20px; background:   radial-gradient(circle at 100% 50%, transparent 20%, #7BC17E 21%, #A5E1A6 34%, transparent 35%, transparent),   radial-gradient(circle at 0% 50%, transparent 20%, #A5E1A6 21%, #7BC17E 34%, transparent 35%, transparent) 0 -25px; background-color: #96DD99; background-size: 35px 50px;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('24','2','Closet',null,'<div  onClick="select()" id="drag" class="component drag closet"><div class="closet-door"><div class="closet-door-inner"></div></div><div class="closet-body"></div></div>',to_date('28.08.2023 09:05:28','DD.MM.RRRR HH24:MI:SS'),null,to_date('28.08.2023 09:05:28','DD.MM.RRRR HH24:MI:SS'),null,'.closet{ width: 80px; height: 100px; display: flex;   flex-wrap: nowrap;   flex-direction: row;}.closet-door{ width: 40%; height: 100%;}.closet-door-inner{ background-color: black; width: 2px; height: 90%; transform: skew(-20deg, 0deg); float: right; margin-right: 45%;}.closet-body{ width: 60%; height: 100%; background-color: #D7C0A2; border: 1px solid #6F6353;  background-repeat:no-repeat;   background-position:center center;   background-size: 100% 100%, auto;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('25','1','Gate',null,'<div onClick="select()" id="drag" class="component drag gate"><div class="gate-base"></div><div class="gate-top"></div><div class="gate-base"></div></div>',to_date('28.08.2023 09:46:41','DD.MM.RRRR HH24:MI:SS'),null,to_date('28.08.2023 09:46:41','DD.MM.RRRR HH24:MI:SS'),null,'.gate {   height: 10px;   width: 100px;   flex-wrap: nowrap;     display: flex; }  .gate-top {   background: repeating-linear-gradient(to right, #f65252, #f66752 10px, #ffffff 10px, #f0eeea 20px);   height: 10px;   width: 100%;   border: 1px solid black; } .gate-base{   width:10px;   height: 10px;   border-radius: 20px;   border: 1px solid black;   background-color: #e1e1e1; }');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('1','1','Parking space horizontal',null,'<div id="drag" onClick="select()" class=" component left-col drag parking-space"></div>',to_date('19.07.2023 07:09:45','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 07:09:45','DD.MM.RRRR HH24:MI:SS'),null,'.parking-space {height: 50px;width: 100px;background-color: lightblue;border: 1px solid gray;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('2','2','Desk simple horizontal',null,'<div  onClick="select()" id="drag" class="component drag ui-draggable ui-draggable-handle desk-simple horizontal"><div class="monitor-base"></div><div class="monitor-display"></div></div>',to_date('19.07.2023 07:09:45','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 07:09:45','DD.MM.RRRR HH24:MI:SS'),null,'.desk-simple { border: 1px solid gray; width: 140px; height: 70px; background-color: beige; text-align: -webkit-center; margin: 10px; border-radius: 4px; } .monitor-base { width: 10%; height: 10%; border: 1px solid black; background-color: gray; margin-top: 10px } .monitor-display { width: 60%; height: 10%; border: 1px solid black; background-color: gray; }');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('3','1','Parking space paraplegic horizontal',null,'<div onClick="select()" id="drag" class=" component right-col drag parking-space-paraplegic parking-space-paraplegic-horizontal"><i class="fa fa-wheelchair"></i></div>',to_date('19.07.2023 08:06:24','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 08:06:24','DD.MM.RRRR HH24:MI:SS'),null,'.parking-space-paraplegic {background: url("data:image/svg+xml;utf8,<svg xmlns=''http://www.w3.org/2000/svg'' version=''1.1'' preserveAspectRatio=''none'' viewBox=''0 0 100 100''><path d=''M100 0 L0 100 '' stroke=''white'' stroke-width=''4''/><path d=''M0 0 L100 100 '' stroke=''white'' stroke-width=''4''/></svg>");background-repeat: no-repeat;background-position: center center;background-size: 100% 100%, auto;border: solid #0079ff 1px;background-color: #0079ff;text-align-last: center;writing-mode: vertical-lr;}.parking-space {height: 50px;width: 100px;background-color: lightblue;border: 1px solid gray;}.parking-space-paraplegic-horizontal {width: 100px;height: 70px;}.fa-wheelchair {color: white;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('6','2','Wall',null,'<div  onClick="select()" id="drag"  class="drag component wall-office"></div>',to_date('19.07.2023 08:13:29','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 08:13:29','DD.MM.RRRR HH24:MI:SS'),null,'.wall {width: 80px;height: 20px;border: 1px solid brown;background-image: repeating-linear-gradient(45deg,lightgray 10px,lightgray 12px,beige 12px,beige 20px);}.wall-office {width: 200px;height: 10px;border: 1px solid gray;background-image: repeating-linear-gradient(45deg,lightgray 10px,lightgray 12px,beige 12px,beige 20px);}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('7','1','Parking space vertical',null,'<div id="drag" onClick="select()"  class="component  left-col drag parking-space-vertical"></div>',to_date('19.07.2023 08:13:30','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 08:13:30','DD.MM.RRRR HH24:MI:SS'),null,'.parking-space {height: 50px;width: 100px;background-color: lightblue;border: 1px solid gray;}.parking-space-vertical {height: 100px;width: 50px;background-color: lightblue;border: 1px solid gray;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('8','1','Parking space paraplegic vertical',null,'<div onClick="select()" id="drag" class="component drag parking-space-paraplegic parking-space-paraplegic-vertical"><i class="fa fa-wheelchair"></i></div>',to_date('19.07.2023 08:13:30','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 08:13:30','DD.MM.RRRR HH24:MI:SS'),null,'.parking-space-paraplegic {background: url("data:image/svg+xml;utf8,<svg xmlns=''http://www.w3.org/2000/svg'' version=''1.1'' preserveAspectRatio=''none'' viewBox=''0 0 100 100''><path d=''M100 0 L0 100 '' stroke=''white'' stroke-width=''4''/><path d=''M0 0 L100 100 '' stroke=''white'' stroke-width=''4''/></svg>");background-repeat: no-repeat;background-position: center center;background-size: 100% 100%, auto;border: solid #0079ff 1px;background-color: #0079ff;text-align-last: center;writing-mode: vertical-lr;}.parking-space {height: 50px;width: 100px;background-color: lightblue;border: 1px solid gray;}.parking-space-paraplegic-vertical {width: 70px;height: 100px;}.fa-wheelchair {color: white;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('9','1','Wall',null,'<div onClick="select()"  id="drag" class="component drag wall"></div>',to_date('19.07.2023 08:14:45','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 08:14:45','DD.MM.RRRR HH24:MI:SS'),null,'.wall {width: 80px;height: 20px;border: 1px solid brown;background-image: repeating-linear-gradient(45deg,lightgray 10px,lightgray 12px,beige 12px,beige 20px);}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('10','3','Label',null,'<div onClick="select()" id="drag" class="component drag label"><input type="text" value="Label" class="ignore-selected"></div>',to_date('19.07.2023 08:14:45','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 08:14:45','DD.MM.RRRR HH24:MI:SS'),null,'.label{padding: 10px;border: 1px dashed lightblue;height: 50px;}.label>input {border: none;background-color: transparent;}.label>input {border: none;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('11','3','Arrow',null,'<div onClick="select()" id="drag" class="component drag arrow arrow-left"><i class="fa fa-arrow-left"></i></div>',to_date('19.07.2023 08:14:45','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 08:14:45','DD.MM.RRRR HH24:MI:SS'),null,'.arrow {padding: 10px;border: 1px dashed #cccaca !important;display: inline-flex;background-color: transparent !important;height: 50px;}.arrow>i {text-shadow: 1px 2px 2px #808080bd;}@media (max-width: 767px) {.arrow {align-items: center;justify-content: center;padding: 0px;}}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('12','3','Entrance',null,'<div onClick="select()" id="drag" class="component drag entrance arrow-in-east"><i class="fa fa-box-arrow-in-east"></i></div>',to_date('19.07.2023 08:14:45','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 08:14:45','DD.MM.RRRR HH24:MI:SS'),null,'.entrance {padding: 10px;border: 1px solid #cccaca !important;display: inline-flex;background-color: white !important;height: 50px;}.entrance>i {text-shadow: 1px 2px 2px #808080bd;}@media (max-width: 767px) {.entrance {align-items: center;justify-content: center;padding: 0px;}}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('19','2','Couch',null,'<div id="drag" onClick="select()" class="component drag workspace-couch"><div class="workspace-couch-top"></div><div class="workspace-couch-seat seat-left"></div><div class="workspace-couch-seat"></div></div>',to_date('22.08.2023 10:57:22','DD.MM.RRRR HH24:MI:SS'),null,to_date('22.08.2023 10:57:22','DD.MM.RRRR HH24:MI:SS'),null,'.workspace-couch {  width: 140px;  height: 50px;  background-color: #A1CCD1;  border: 1px solid black;  border-radius: 10px 10px 0px 0px;   display: flex;    flex-wrap: wrap;    flex-direction: row;    text-align: center;}.workspace-couch-top {    margin: 0px 1px 0px 1px;  border: 1px solid black;  width: 100%;  height: 20%;  border-radius: 2px;  background-color: #A1CCD1;}.workspace-couch-seat {  margin: 0% 1% 0px 0%;  border: 1px solid black;  width: 46%;  height: 70%;  border-radius: 2px;  background-color: #A1CCD1;}.seat-left{  margin-left: 2%;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('20','2','Plant',null,'<div id="drag" onClick="select()" class="component drag plant-container"><div class="pot"><div class="leaf leaf1"></div><div class="leaf leaf2"></div><div class="leaf leaf3"></div><div class="leaf leaf4"></div></div></div>',to_date('22.08.2023 10:57:22','DD.MM.RRRR HH24:MI:SS'),null,to_date('22.08.2023 10:57:22','DD.MM.RRRR HH24:MI:SS'),null,'.plant-container { display: flex; align-items: center;}.pot {display: flex;   flex-direction: row;   align-items: center;   justify-content: space-between;   width: 50px;   height: 50px;   background-color: #ca8451;   border-radius: 50%;   flex-wrap: wrap;   align-content: center;   border: 1px solid black;}.leaf { width: 45%; height: 43%; background-color: #7BC17E; border-radius: 0px 10px 0px 10px; border: 1px solid darkgreen;}.leaf2 { transform: rotate(90deg);}.leaf3 { transform: rotate(270deg);}.leaf4 { transform: rotate(180deg);}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('13','3','Door',null,'<div onClick="select()" id="drag" class="component drag door"><div class="door-wing"></div></div>',to_date('19.07.2023 12:44:44','DD.MM.RRRR HH24:MI:SS'),null,to_date('19.07.2023 12:44:44','DD.MM.RRRR HH24:MI:SS'),null,'.door {border: 1px solid gray;width: 80px;height: 80px;border-radius: 0px 0px 80px 0px;text-align: left;border-top: none;background-color: white;overflow: inherit;}.door-wing {width: 5px;height: 80px;background-color: white;border: 1px solid gray;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('21','3','Door right',null,'<div onClick="select()" id="drag" class="component drag door-right"><div class="door-wing-right"></div></div>',to_date('23.08.2023 10:04:57','DD.MM.RRRR HH24:MI:SS'),null,to_date('23.08.2023 10:04:57','DD.MM.RRRR HH24:MI:SS'),null,'.door {border: 1px solid gray;width: 80px;height: 80px;border-radius: 0px 0px 80px 0px;text-align: left;border-top: none;background-color: white;overflow: inherit;}.door-right {   border: 1px solid gray;   width: 80px;   height: 80px;   border-radius: 0px 0px 0px 80px;   text-align: left;   border-top: none;   background-color: white;   overflow: inherit;}.door-wing-right {   width: 5px;   height: 80px;   float: right;   background-color: white;   border: 1px solid gray;}.door-wing {width: 5px;height: 80px;background-color: white;border: 1px solid gray;}');
Insert into TYPE_COMPONENT (ID,PLAN_TYPE_ID,NAME,DESCRIPTION,CODE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,CSS) values ('22','2','Chair',null,'<div onClick="select()" id="drag" class="component drag workspace-chair"><div class="workspace-chair-top"></div><div class="workspace-chair-seat"></div></div>',to_date('23.08.2023 10:29:34','DD.MM.RRRR HH24:MI:SS'),null,to_date('23.08.2023 10:29:34','DD.MM.RRRR HH24:MI:SS'),null,'.workspace-chair { width: 60px; height: 50px; background-color: #E9B384; border: 1px solid black; border-radius: 20px 20px 2px 2px;  display: flex;   flex-wrap: wrap;   flex-direction: row;   text-align: center;}.workspace-chair-top {   margin: 5% 5% 0px 5%; border: 1px solid black; width: 90%; height: 20%; background-color: #E9B384; border-radius: 20px 20px 2px 2px;}.workspace-chair-seat { margin: 0% 10% 0px 10%; border: 1px solid black; width: 80%; height: 70%; border-radius: 0% 0% 15% 15%; background-color: #E9B384;}');

--------------------------------------------------------
--  Constraints for Table PLAN_TYPE
--------------------------------------------------------

  ALTER TABLE "PLAN_TYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PLAN_TYPE" ADD CONSTRAINT "PLAN_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table TYPE_COMPONENT
--------------------------------------------------------
  ALTER TABLE "TYPE_COMPONENT" MODIFY ("ID" CONSTRAINT "NNC_PLAN_TYPEV1_ID" NOT NULL ENABLE);
  ALTER TABLE "TYPE_COMPONENT" MODIFY ("PLAN_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "TYPE_COMPONENT" ADD CONSTRAINT "TYPE_COMPONENT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
